### ISSUE TITLE
Plugin error

### ISSUE THREAD

**Issue by AlineCGR** [lmotta/mapbiomascollection#2]
Hello,

I tried to use the Plugin but I got this message:

MapBiomasCollection: Error server: Get url=http://workspace.mapbiomas.org/wms?map=wms/v/4.1/classification/coverage.map

What could I do?

Thank you !

**Comment by lmotta** [comment]
Hi Aline,

The WMS server of MapBiomas Collection is updating for collection 5.
The staff is working for WMS stay compatible with QGIS.

Thanks for your interest.
