### ISSUE TITLE
Erro de servidor no plugin do Qgis (?)

### ISSUE THREAD

**Issue by duardoas** [lmotta/mapbiomascollection#4]

**Comment by duardoas** [comment]
Não consigo acessar o plugin após instalar. Aparece uma mensagem de erro
![Captura de Tela (25)](https://user-images.githubusercontent.com/91424585/134814045-e4d3713c-953c-4128-84e2-b120be0b1f94.png)

**Comment by lmotta** [comment]
O erro está no servidor do mapbiomas.
Reporte o erro no site do MapBiomas:
https://mapbiomas.org/contato
